# Generated by Django 5.1.11 on 2025-09-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fno-photo-available&psig=AOvVaw00wrOab8uY1Odlq4kye_UV&ust=1758228227393000&source=images&cd=vfe&opi=89978449&ved=0CBYQjRxqFwoTCJCPvumS3o8DFQAAAAAdAAAAABAV', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fno-photo-available&psig=AOvVaw00wrOab8uY1Odlq4kye_UV&ust=1758228227393000&source=images&cd=vfe&opi=89978449&ved=0CBYQjRxqFwoTCJCPvumS3o8DFQAAAAAdAAAAABAV', max_length=500),
        ),
    ]
