# Generated by Django 5.1.11 on 2025-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobby_image_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930', max_length=500),
        ),
    ]
